import type { CSSProperties } from "react";
import { PICKER_MAX_WIDTH } from "./constants";

/** Co-located styles for the shared project-context picker. */
export const s = {
  wrap: { maxWidth: PICKER_MAX_WIDTH } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 10 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  headerRight: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  filterBox: { width: 220 } satisfies CSSProperties,
  caption: {
    fontSize: 13,
    lineHeight: 1.6,
    color: "var(--text-muted)",
    marginBottom: 18,
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: (dim: boolean, dropTarget: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid " + (dropTarget ? "var(--accent)" : "var(--border)"),
    background: "var(--bg-surface)",
    opacity: dim ? 0.55 : 1,
  }),
  handle: {
    display: "inline-flex",
    color: "var(--text-muted)",
    cursor: "grab",
    flexShrink: 0,
  } satisfies CSSProperties,
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  path: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  meta: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  rowRight: { display: "flex", alignItems: "center", gap: 6, flexShrink: 0 } satisfies CSSProperties,
  noMatch: { fontSize: 13, color: "var(--text-muted)", padding: "18px 2px" } satisfies CSSProperties,
  error: { fontSize: 13, color: "var(--crit)", marginBottom: 12 } satisfies CSSProperties,
  /** Caveat banner — sits ABOVE the rows, never in place of them. */
  banner: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 14,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
    fontSize: 12,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  bannerTitle: {
    display: "block",
    fontWeight: 650,
    color: "var(--text-primary)",
    marginBottom: 2,
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 14,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  warn: {
    marginTop: 12,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    color: "var(--text-primary)",
    fontSize: 12,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  /** SERIALIZES AS panel — the literal prompt text, so it reads as code. */
  serialized: { marginTop: 20 } satisfies CSSProperties,
  serializedLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  serializedBlock: {
    margin: 0,
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-secondary)",
    fontSize: 12,
    lineHeight: 1.65,
    // Wide delimiter lines scroll inside the panel rather than widening the tab.
    overflowX: "auto",
    whiteSpace: "pre",
  } satisfies CSSProperties,
  serializedMissing: {
    marginTop: 8,
    fontSize: 12,
    lineHeight: 1.6,
    color: "var(--warn)",
  } satisfies CSSProperties,
  previewBody: {
    padding: "4px 2px",
    fontSize: 13,
    color: "var(--text-primary)",
    overflowY: "auto",
    maxHeight: "62vh",
  } satisfies CSSProperties,
  previewLoading: { fontSize: 13, color: "var(--text-muted)", padding: "18px 2px" } satisfies CSSProperties,
} as const;
