import type { CSSProperties } from "react";
import { CARD_GRID_COLS, PREVIEW_WIDTH } from "./constants";

/** Co-located styles for SkillsListView. */
export const s = {
  page: { padding: "24px 32px 44px", maxWidth: 1240, margin: "0 auto" } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 14, marginBottom: 20 } satisfies CSSProperties,
  headerText: { flex: 1 } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 220,
  } satisfies CSSProperties,
  searchIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  columns: { display: "flex", gap: 20, alignItems: "flex-start" } satisfies CSSProperties,
  gridCol: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  grid: { display: "grid", gridTemplateColumns: CARD_GRID_COLS, gap: 14 } satisfies CSSProperties,
  preview: {
    width: PREVIEW_WIDTH,
    flexShrink: 0,
    position: "sticky",
    top: 16,
    border: "1px solid var(--border)",
    borderRadius: 9,
    background: "var(--bg-surface)",
    padding: 16,
    maxHeight: "calc(100vh - 120px)",
    overflow: "auto",
  } as CSSProperties,
  previewHeader: { display: "flex", alignItems: "center", gap: 8, marginBottom: 10 } satisfies CSSProperties,
  previewName: { fontSize: 15, fontWeight: 700, flex: 1, minWidth: 0 } satisfies CSSProperties,
  previewBadges: { display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 12 } satisfies CSSProperties,
  previewBody: {
    fontSize: 13,
    color: "var(--text-secondary)",
    borderTop: "1px solid var(--border)",
    paddingTop: 12,
  } satisfies CSSProperties,
  previewActions: { marginTop: 14 } satisfies CSSProperties,
  untrusted: {
    display: "flex",
    gap: 8,
    padding: "8px 10px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-hover)",
    fontSize: 12,
    lineHeight: 1.45,
    color: "var(--text-secondary)",
    marginBottom: 12,
  } satisfies CSSProperties,
} as const;
